name: Update Submodules
permissions:
  contents: write

on:
  schedule:
    # Run every Saturday at 20:00 UTC
    - cron: '0 20 * * 6'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Update Submodules
      run: |
          git submodule foreach git pull origin main
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GH_PATOKEN }}
        commit-message: Update submodules, update snapshots
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        title: 'Update submodules'
        body: Update submodules to their latest versions as well as add new snapshots
        branch: update-submodules
        delete-branch: true
        assignees: jskherman
